local _, ts = ...

-- Auto-generated from Wowhead CATA talent calculator data
-- Run: uv run --project tools tools/generate_wowhead_data.py cata --fetch <output>
-- Single-point tokens: abcdefghjkmnpqrstvwzxyilou468-~!
-- Max-rank tokens: ABCDEFGHJKMNPQRSTVWZXYILOU579_^.
-- Baseline talent level: 10
-- Point-grant levels: 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 81, 82, 83, 84, 85

ts.WowheadData = {
    cata = {
        __meta = {
            singlePointTokens = "abcdefghjkmnpqrstvwzxyilou468-~!",
            maxRankTokens = "ABCDEFGHJKMNPQRSTVWZXYILOU579_^.",
            startingLevel = 9,
            pointGrantLevels = {10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 81, 82, 83, 84, 85},
        },
        DEATHKNIGHT = {
            [0] = { -- A dark guardian who manipulates and corrupts life energy to sustain <him/her>self in the face of an enemy onslaught.
                ["a"] = { name = "Butchery", icon = "inv_axe_68", ranks = {48979, 49483} },
                ["b"] = { name = "Blade Barrier", icon = "ability_upgrademoonglaive", ranks = {49182, 49500, 49501} },
                ["c"] = { name = "Bladed Armor", icon = "inv_shoulder_36", ranks = {48978, 49390, 49391} },
                ["d"] = { name = "Improved Blood Tap", icon = "spell_deathknight_bloodtap", ranks = {94553, 94555} },
                ["e"] = { name = "Scent of Blood", icon = "ability_rogue_bloodyeye", ranks = {49004, 49508, 49509} },
                ["f"] = { name = "Scarlet Fever", icon = "ability_rogue_vendetta", ranks = {81131, 81132} },
                ["g"] = { name = "Hand of Doom", icon = "ability_deathknight_desolation", ranks = {85793, 85794} },
                ["h"] = { name = "Blood-Caked Blade", icon = "ability_criticalstrike", ranks = {49219, 49627, 49628} },
                ["j"] = { name = "Bone Shield", icon = "ability_deathknight_boneshield", ranks = {49222} },
                ["k"] = { name = "Toughness", icon = "spell_holy_devotion", ranks = {49042, 49786, 49787} },
                ["m"] = { name = "Abomination's Might", icon = "ability_warrior_intensifyrage", ranks = {53137, 53138} },
                ["n"] = { name = "Sanguine Fortitude", icon = "ability_deathknight_sanguinfortitude", ranks = {81125, 81127} },
                ["p"] = { name = "Blood Parasite", icon = "spell_shadow_soulleech", ranks = {49027, 49542} },
                ["q"] = { name = "Improved Blood Presence", icon = "spell_deathknight_bloodpresence", ranks = {50365, 50371} },
                ["r"] = { name = "Will of the Necropolis", icon = "ability_creature_cursed_02", ranks = {52284, 81163, 81164} },
                ["s"] = { name = "Rune Tap", icon = "spell_deathknight_runetap", ranks = {48982} },
                ["t"] = { name = "Vampiric Blood", icon = "spell_shadow_lifedrain", ranks = {55233} },
                ["v"] = { name = "Improved Death Strike", icon = "spell_deathknight_butcher2", ranks = {62905, 62908, 81138} },
                ["w"] = { name = "Crimson Scourge", icon = "spell_deathknight_bloodboil", ranks = {81135, 81136} },
                ["z"] = { name = "Dancing Rune Weapon", icon = "inv_sword_07", ranks = {49028} },
            },
            [1] = { -- An icy harbinger of doom, channeling runic power and delivering rapid weapon strikes.
                ["a"] = { name = "Runic Power Mastery", icon = "spell_arcane_arcane01", ranks = {49455, 50147, 91145} },
                ["b"] = { name = "Icy Reach", icon = "spell_frost_manarecharge", ranks = {55061, 55062} },
                ["c"] = { name = "Nerves of Cold Steel", icon = "ability_dualwield", ranks = {49226, 50137, 50138} },
                ["d"] = { name = "Annihilation", icon = "inv_weapon_hand_18", ranks = {51468, 51472, 51473} },
                ["e"] = { name = "Lichborne", icon = "spell_shadow_raisedead", ranks = {49039} },
                ["f"] = { name = "On a Pale Horse", icon = "ability_mount_undeadhorse", ranks = {51983, 51986} },
                ["g"] = { name = "Endless Winter", icon = "spell_shadow_twilight", ranks = {49137, 49657} },
                ["h"] = { name = "Merciless Combat", icon = "inv_sword_112", ranks = {49024, 49538} },
                ["j"] = { name = "Chill of the Grave", icon = "spell_frost_frostshock", ranks = {49149, 50115} },
                ["k"] = { name = "Killing Machine", icon = "inv_sword_122", ranks = {51123, 51127, 51128} },
                ["m"] = { name = "Rime", icon = "spell_frost_freezingbreath", ranks = {49188, 56822, 59057} },
                ["n"] = { name = "Pillar of Frost", icon = "ability_deathknight_pillaroffrost", ranks = {51271} },
                ["p"] = { name = "Improved Icy Talons", icon = "spell_deathknight_icytalons", ranks = {55610} },
                ["q"] = { name = "Brittle Bones", icon = "ability_deathknight_brittlebones", ranks = {81327, 81328} },
                ["r"] = { name = "Chilblains", icon = "spell_frost_wisp", ranks = {50040, 50041} },
                ["s"] = { name = "Hungering Cold", icon = "inv_staff_15", ranks = {49203} },
                ["t"] = { name = "Improved Frost Presence", icon = "spell_deathknight_frostpresence", ranks = {50384, 50385} },
                ["v"] = { name = "Threat of Thassarian", icon = "ability_dualwieldspecialization", ranks = {65661, 66191, 66192} },
                ["w"] = { name = "Might of the Frozen Wastes", icon = "inv_sword_120", ranks = {81330, 81332, 81333} },
                ["z"] = { name = "Howling Blast", icon = "spell_frost_arcticwinds", ranks = {49184} },
            },
            [2] = { -- A master of death and decay, spreading infection and controlling undead minions to do <his/her> bidding.
                ["a"] = { name = "Unholy Command", icon = "spell_deathknight_strangulate", ranks = {49588, 49589} },
                ["b"] = { name = "Virulence", icon = "spell_shadow_burningspirit", ranks = {48962, 49567, 49568} },
                ["c"] = { name = "Epidemic", icon = "spell_shadow_shadowwordpain", ranks = {49036, 49562, 81334} },
                ["d"] = { name = "Desecration", icon = "spell_shadow_shadowfiend", ranks = {55666, 55667} },
                ["e"] = { name = "Resilient Infection", icon = "ability_creature_disease_05", ranks = {81338, 81339} },
                ["f"] = { name = "Morbidity", icon = "spell_shadow_deathanddecay", ranks = {48963, 49564, 49565} },
                ["g"] = { name = "Runic Corruption", icon = "spell_shadow_rune", ranks = {51459, 51462} },
                ["h"] = { name = "Unholy Frenzy", icon = "spell_shadow_unholyfrenzy", ranks = {49016} },
                ["j"] = { name = "Contagion", icon = "spell_shadow_plaguecloud", ranks = {91316, 91319} },
                ["k"] = { name = "Shadow Infusion", icon = "spell_shadow_requiem", ranks = {48965, 49571, 49572} },
                ["m"] = { name = "Death's Advance", icon = "spell_shadow_demonicempathy", ranks = {96269, 96270} },
                ["n"] = { name = "Magic Suppression", icon = "spell_shadow_antimagicshell", ranks = {49224, 49610, 49611} },
                ["p"] = { name = "Rage of Rivendare", icon = "inv_weapon_halberd14", ranks = {51745, 51746, 91323} },
                ["q"] = { name = "Unholy Blight", icon = "spell_shadow_contagion", ranks = {49194} },
                ["r"] = { name = "Anti-Magic Zone", icon = "spell_deathknight_antimagiczone", ranks = {51052} },
                ["s"] = { name = "Improved Unholy Presence", icon = "spell_deathknight_unholypresence", ranks = {50391, 50392} },
                ["t"] = { name = "Dark Transformation", icon = "achievement_boss_festergutrotface", ranks = {63560} },
                ["v"] = { name = "Ebon Plaguebringer", icon = "ability_creature_cursed_03", ranks = {51099, 51160} },
                ["w"] = { name = "Sudden Doom", icon = "spell_shadow_painspike", ranks = {49018, 49529, 49530} },
                ["z"] = { name = "Summon Gargoyle", icon = "ability_deathknight_summongargoyle", ranks = {49206} },
            },
        },
        DRUID = {
            [0] = { -- Can take on the form of a powerful Moonkin, balancing the power of Arcane and Nature magic to destroy enemies at a distance.
                ["a"] = { name = "Nature's Grace", icon = "spell_nature_naturesblessing", ranks = {16880, 61345, 61346} },
                ["b"] = { name = "Starlight Wrath", icon = "spell_nature_abolishmagic", ranks = {16814, 16815, 16816} },
                ["c"] = { name = "Nature's Majesty", icon = "inv_staff_01", ranks = {35363, 35364} },
                ["d"] = { name = "Genesis", icon = "spell_arcane_arcane03", ranks = {57810, 57811, 57812} },
                ["e"] = { name = "Moonglow", icon = "spell_nature_sentinal", ranks = {16845, 16846, 16847} },
                ["f"] = { name = "Balance of Power", icon = "ability_druid_balanceofpower", ranks = {33592, 33596} },
                ["g"] = { name = "Euphoria", icon = "achievement_boss_valithradreamwalker", ranks = {81061, 81062} },
                ["h"] = { name = "Moonkin Form", icon = "spell_nature_forceofnature", ranks = {24858} },
                ["j"] = { name = "Typhoon", icon = "ability_druid_typhoon", ranks = {50516} },
                ["k"] = { name = "Shooting Stars", icon = "ability_mage_arcanebarrage", ranks = {93398, 93399} },
                ["m"] = { name = "Owlkin Frenzy", icon = "ability_druid_owlkinfrenzy", ranks = {48389, 48392, 48393} },
                ["n"] = { name = "Gale Winds", icon = "ability_druid_galewinds", ranks = {48488, 48514} },
                ["p"] = { name = "Solar Beam", icon = "ability_vehicle_sonicshockwave", ranks = {78675} },
                ["q"] = { name = "Dreamstate", icon = "ability_druid_dreamstate", ranks = {33597, 33599} },
                ["r"] = { name = "Force of Nature", icon = "ability_druid_forceofnature", ranks = {33831} },
                ["s"] = { name = "Sunfire", icon = "ability_mage_firestarter", ranks = {93401} },
                ["t"] = { name = "Earth and Moon", icon = "ability_druid_earthandsky", ranks = {48506} },
                ["v"] = { name = "Fungal Growth", icon = "creature_sporemushroom", ranks = {78788, 78789} },
                ["w"] = { name = "Lunar Shower", icon = "achievement_worldevent_lunar", ranks = {33603, 33604, 33605} },
                ["z"] = { name = "Starfall", icon = "ability_druid_starfall", ranks = {48505} },
            },
            [1] = { -- Takes on the form of a great cat to deal damage with bleeds and bites or a mighty bear to absorb damage and protect allies.
                ["a"] = { name = "Feral Swiftness", icon = "spell_nature_spiritwolf", ranks = {17002, 24866} },
                ["b"] = { name = "Furor", icon = "spell_holy_blessingofstamina", ranks = {17056, 17058, 17059} },
                ["c"] = { name = "Predatory Strikes", icon = "ability_hunter_pet_cat", ranks = {16972, 16974} },
                ["d"] = { name = "Infected Wounds", icon = "ability_druid_infectedwound", ranks = {48483, 48484} },
                ["e"] = { name = "Fury Swipes", icon = "ability_druid_mangle-tga", ranks = {48532, 80552, 80553} },
                ["f"] = { name = "Primal Fury", icon = "ability_racial_cannibalize", ranks = {37116, 37117} },
                ["g"] = { name = "Feral Aggression", icon = "classic_ability_druid_demoralizingroar", ranks = {16858, 16859} },
                ["h"] = { name = "King of the Jungle", icon = "ability_druid_kingofthejungle", ranks = {48492, 48494, 48495} },
                ["j"] = { name = "Feral Charge", icon = "ability_hunter_pet_bear", ranks = {49377} },
                ["k"] = { name = "Stampede", icon = "spell_druid_feralchargecat", ranks = {78892, 78893} },
                ["m"] = { name = "Thick Hide", icon = "inv_misc_pelt_bear_03", ranks = {16929, 16930, 16931} },
                ["n"] = { name = "Leader of the Pack", icon = "spell_nature_unyeildingstamina", ranks = {17007} },
                ["p"] = { name = "Brutal Impact", icon = "ability_druid_bash", ranks = {16940, 16941} },
                ["q"] = { name = "Nurturing Instinct", icon = "ability_druid_healinginstincts", ranks = {33872, 33873} },
                ["r"] = { name = "Primal Madness", icon = "ability_mount_jungletiger", ranks = {80316, 80317} },
                ["s"] = { name = "Survival Instincts", icon = "ability_druid_tigersroar", ranks = {61336} },
                ["t"] = { name = "Endless Carnage", icon = "spell_deathknight_bloodboil", ranks = {80314, 80315} },
                ["v"] = { name = "Natural Reaction", icon = "ability_bullrush", ranks = {57878, 57880} },
                ["w"] = { name = "Blood in the Water", icon = "inv_misc_food_134_meat", ranks = {80318, 80319} },
                ["z"] = { name = "Rend and Tear", icon = "ability_druid_primalagression", ranks = {48432, 48433, 48434} },
                ["x"] = { name = "Pulverize", icon = "ability_smash", ranks = {80313} },
                ["y"] = { name = "Berserk", icon = "ability_druid_berserk", ranks = {50334} },
            },
            [2] = { -- Uses heal-over-time Nature spells to keep allies alive, taking on the form of a tree when the need is most urgent.
                ["a"] = { name = "Blessing of the Grove", icon = "spell_shaman_spiritlink", ranks = {78784, 78785} },
                ["b"] = { name = "Natural Shapeshifter", icon = "spell_nature_wispsplode", ranks = {16833, 16834} },
                ["c"] = { name = "Naturalist", icon = "spell_nature_healingtouch", ranks = {17069, 17070} },
                ["d"] = { name = "Heart of the Wild", icon = "spell_holy_blessingofagility", ranks = {17003, 17004, 17005} },
                ["e"] = { name = "Perseverance", icon = "achievement_zone_darnassus", ranks = {78734, 78735, 78736} },
                ["f"] = { name = "Master Shapeshifter", icon = "ability_druid_mastershapeshifter", ranks = {48411} },
                ["g"] = { name = "Improved Rejuvenation", icon = "spell_nature_rejuvenation", ranks = {17111, 17112, 17113} },
                ["h"] = { name = "Living Seed", icon = "ability_druid_giftoftheearthmother", ranks = {48496, 48499, 48500} },
                ["j"] = { name = "Revitalize", icon = "ability_druid_replenish", ranks = {48539, 48544} },
                ["k"] = { name = "Nature's Swiftness", icon = "spell_nature_ravenform", ranks = {17116} },
                ["m"] = { name = "Fury of Stormrage", icon = "inv_staff_90", ranks = {17104, 24943} },
                ["n"] = { name = "Nature's Bounty", icon = "spell_nature_resistnature", ranks = {17074, 17075, 17076} },
                ["p"] = { name = "Empowered Touch", icon = "ability_druid_empoweredtouch", ranks = {33879, 33880} },
                ["q"] = { name = "Malfurion's Gift", icon = "spell_shaman_giftearthmother", ranks = {92363, 92364} },
                ["r"] = { name = "Efflorescence", icon = "inv_misc_herb_talandrasrose", ranks = {34151, 81274, 81275} },
                ["s"] = { name = "Wild Growth", icon = "ability_druid_flourish", ranks = {48438} },
                ["t"] = { name = "Nature's Cure", icon = "ability_shaman_cleansespirit", ranks = {88423} },
                ["v"] = { name = "Nature's Ward", icon = "ability_druid_naturalperfection", ranks = {33881, 33882} },
                ["w"] = { name = "Gift of the Earthmother", icon = "ability_druid_manatree", ranks = {51179, 51180, 51181} },
                ["z"] = { name = "Swift Rejuvenation", icon = "ability_druid_empoweredrejuvination", ranks = {33886} },
                ["x"] = { name = "Tree of Life", icon = "ability_druid_treeoflife", ranks = {33891} },
            },
        },
        HUNTER = {
            [0] = { -- A master of the wild who can tame a wide variety of beasts to assist <him/her> in combat.
                ["a"] = { name = "Improved Kill Command", icon = "ability_hunter_silenthunter", ranks = {35029, 35030} },
                ["b"] = { name = "One with Nature", icon = "ability_hunter_onewithnature", ranks = {82682, 82683, 82684} },
                ["c"] = { name = "Bestial Discipline", icon = "ability_hunter_bestialdiscipline", ranks = {19590, 19592, 82687} },
                ["d"] = { name = "Pathfinding", icon = "ability_hunter_pathfinding2", ranks = {19559, 19560} },
                ["e"] = { name = "Spirit Bond", icon = "classic_ability_druid_demoralizingroar", ranks = {19578, 20895} },
                ["f"] = { name = "Frenzy", icon = "inv_misc_monsterclaw_03", ranks = {19621, 19622, 19623} },
                ["g"] = { name = "Improved Mend Pet", icon = "ability_hunter_mendpet", ranks = {19572, 19573} },
                ["h"] = { name = "Cobra Strikes", icon = "ability_hunter_cobrastrikes", ranks = {53256, 53259, 53260} },
                ["j"] = { name = "Fervor", icon = "ability_hunter_aspectoftheviper", ranks = {82726} },
                ["k"] = { name = "Focus Fire", icon = "ability_hunter_focusfire", ranks = {82692} },
                ["m"] = { name = "Longevity", icon = "ability_hunter_longevity", ranks = {53262, 53263, 53264} },
                ["n"] = { name = "Killing Streak", icon = "achievement_bg_kill_carrier_opposing_flagroom", ranks = {82748, 82749} },
                ["p"] = { name = "Crouching Tiger, Hidden Chimera", icon = "ability_hunter_pet_chimera", ranks = {82898, 82899} },
                ["q"] = { name = "Bestial Wrath", icon = "ability_druid_ferociousbite", ranks = {19574} },
                ["r"] = { name = "Ferocious Inspiration", icon = "ability_hunter_ferociousinspiration", ranks = {34460} },
                ["s"] = { name = "Kindred Spirits", icon = "ability_hunter_separationanxiety", ranks = {56314, 56315} },
                ["t"] = { name = "The Beast Within", icon = "ability_hunter_beastwithin", ranks = {34692} },
                ["v"] = { name = "Invigoration", icon = "ability_hunter_invigeration", ranks = {53252, 53253} },
                ["w"] = { name = "Beast Mastery", icon = "ability_hunter_beastmastery", ranks = {53270} },
            },
            [1] = { -- A master archer or sharpshooter who excels in bringing down enemies from afar.
                ["a"] = { name = "Go for the Throat", icon = "ability_hunter_goforthethroat", ranks = {34950, 34954} },
                ["b"] = { name = "Efficiency", icon = "ability_hunter_focusedaim", ranks = {19416, 19417, 19418} },
                ["c"] = { name = "Rapid Killing", icon = "ability_hunter_rapidkilling", ranks = {34948, 34949} },
                ["d"] = { name = "Sic 'Em!", icon = "ability_hunter_sickem", ranks = {83340, 83356} },
                ["e"] = { name = "Improved Steady Shot", icon = "ability_hunter_improvedsteadyshot", ranks = {53221, 53222, 53224} },
                ["f"] = { name = "Careful Aim", icon = "ability_hunter_zenarchery", ranks = {34482, 34483} },
                ["g"] = { name = "Silencing Shot", icon = "ability_theblackarrow", ranks = {34490} },
                ["h"] = { name = "Concussive Barrage", icon = "ability_hunter_efficiency", ranks = {35100, 35102} },
                ["j"] = { name = "Piercing Shots", icon = "ability_hunter_piercingshots", ranks = {53234, 53237, 53238} },
                ["k"] = { name = "Bombardment", icon = "ability_marksmanship", ranks = {35104, 35110} },
                ["m"] = { name = "Trueshot Aura", icon = "ability_trueshot", ranks = {19506} },
                ["n"] = { name = "Termination", icon = "ability_warrior_focusedrage", ranks = {83489, 83490} },
                ["p"] = { name = "Resistance is Futile", icon = "ability_hunter_resistanceisfutile", ranks = {82893, 82894} },
                ["q"] = { name = "Rapid Recuperation", icon = "ability_hunter_rapidregeneration", ranks = {53228, 53232} },
                ["r"] = { name = "Master Marksman", icon = "ability_hunter_mastermarksman", ranks = {34485, 34486, 34487} },
                ["s"] = { name = "Readiness", icon = "ability_hunter_readiness", ranks = {23989} },
                ["t"] = { name = "Posthaste", icon = "ability_hunter_posthaste", ranks = {83558, 83560} },
                ["v"] = { name = "Marked for Death", icon = "ability_hunter_assassinate", ranks = {53241, 53243} },
                ["w"] = { name = "Chimera Shot", icon = "ability_hunter_chimerashot2", ranks = {53209} },
            },
            [2] = { -- A rugged tracker who favors using animal venom, explosives and traps as deadly weapons.
                ["a"] = { name = "Hunter vs. Wild", icon = "ability_hunter_huntervswild", ranks = {56339, 56340, 56341} },
                ["b"] = { name = "Pathing", icon = "ability_hunter_improvedtracking", ranks = {52783, 52785, 52786} },
                ["c"] = { name = "Improved Serpent Sting", icon = "ability_hunter_quickshot", ranks = {19464, 82834} },
                ["d"] = { name = "Survival Tactics", icon = "ability_rogue_feigndeath", ranks = {19286, 19287} },
                ["e"] = { name = "Trap Mastery", icon = "ability_ensnare", ranks = {19376, 63457, 63458} },
                ["f"] = { name = "Entrapment", icon = "spell_nature_stranglevines", ranks = {19184, 19387} },
                ["g"] = { name = "Point of No Escape", icon = "ability_hunter_pointofnoescape", ranks = {53298, 53299} },
                ["h"] = { name = "Thrill of the Hunt", icon = "ability_hunter_thrillofthehunt", ranks = {34497, 34498, 34499} },
                ["j"] = { name = "Counterattack", icon = "ability_warrior_challange", ranks = {19306} },
                ["k"] = { name = "Lock and Load", icon = "ability_hunter_lockandload", ranks = {56342, 56343} },
                ["m"] = { name = "Resourcefulness", icon = "ability_hunter_resourcefulness", ranks = {34491, 34492, 34493} },
                ["n"] = { name = "Mirrored Blades", icon = "inv_weapon_shortblade_99", ranks = {83494, 83495} },
                ["p"] = { name = "T.N.T.", icon = "inv_misc_bomb_05", ranks = {56333, 56336} },
                ["q"] = { name = "Toxicology", icon = "inv_alchemy_enchantedvial", ranks = {82832, 82833} },
                ["r"] = { name = "Wyvern Sting", icon = "inv_spear_02", ranks = {19386} },
                ["s"] = { name = "Noxious Stings", icon = "ability_hunter_potentvenom", ranks = {53295, 53296} },
                ["t"] = { name = "Hunting Party", icon = "ability_hunter_huntingparty", ranks = {53290} },
                ["v"] = { name = "Sniper Training", icon = "ability_hunter_longshots", ranks = {53302, 53303, 53304} },
                ["w"] = { name = "Serpent Spread", icon = "ability_hunter_serpentswiftness", ranks = {87934, 87935} },
                ["z"] = { name = "Black Arrow", icon = "spell_shadow_painspike", ranks = {3674} },
            },
        },
        MAGE = {
            [0] = { -- Manipulates arcane energies, playing with the very fabric of time and space.
                ["a"] = { name = "Arcane Concentration", icon = "spell_shadow_manaburn", ranks = {11213, 12574, 12575} },
                ["b"] = { name = "Improved Counterspell", icon = "spell_frost_iceshock", ranks = {11255, 12598} },
                ["c"] = { name = "Netherwind Presence", icon = "ability_mage_netherwindpresence", ranks = {44400, 44402, 44403} },
                ["d"] = { name = "Torment the Weak", icon = "spell_arcane_focusedpower", ranks = {29447, 55339, 55340} },
                ["e"] = { name = "Invocation", icon = "spell_arcane_invocation", ranks = {84722, 84723} },
                ["f"] = { name = "Improved Arcane Missiles", icon = "spell_nature_starfall", ranks = {83513, 83515} },
                ["g"] = { name = "Improved Blink", icon = "spell_arcane_blink", ranks = {31569, 31570} },
                ["h"] = { name = "Arcane Flows", icon = "ability_mage_potentspirit", ranks = {44378, 44379} },
                ["j"] = { name = "Presence of Mind", icon = "spell_nature_enchantarmor", ranks = {12043} },
                ["k"] = { name = "Missile Barrage", icon = "ability_mage_missilebarrage", ranks = {44404, 54486} },
                ["m"] = { name = "Prismatic Cloak", icon = "spell_arcane_prismaticcloak", ranks = {31574, 31575, 54354} },
                ["n"] = { name = "Improved Polymorph", icon = "spell_nature_polymorph", ranks = {11210, 12592} },
                ["p"] = { name = "Arcane Tactics", icon = "spell_arcane_arcanetactics", ranks = {82930} },
                ["q"] = { name = "Incanter's Absorption", icon = "ability_mage_incantersabsorbtion", ranks = {44394, 44395} },
                ["r"] = { name = "", icon = "", ranks = {90724, 90731} },
                ["s"] = { name = "Improved Arcane Explosion", icon = "spell_nature_wispsplode", ranks = {90787, 90788} },
                ["t"] = { name = "Arcane Potency", icon = "spell_arcane_arcanepotency", ranks = {31571, 31572} },
                ["v"] = { name = "Slow", icon = "spell_nature_slow", ranks = {31589} },
                ["w"] = { name = "Nether Vortex", icon = "spell_arcane_blast", ranks = {86181, 86209} },
                ["z"] = { name = "Focus Magic", icon = "spell_arcane_studentofmagic", ranks = {54646} },
                ["x"] = { name = "Improved Mana Gem", icon = "inv_misc_gem_emerald_01", ranks = {31584, 31585} },
                ["y"] = { name = "Arcane Power", icon = "spell_nature_lightning", ranks = {12042} },
            },
            [1] = { -- Ignites enemies with balls of fire and the breath of dragons.
                ["a"] = { name = "Master of Elements", icon = "spell_fire_masterofelements", ranks = {29074, 29075} },
                ["b"] = { name = "Burning Soul", icon = "spell_burningsoul", ranks = {11083, 84253, 84254} },
                ["c"] = { name = "Improved Fire Blast", icon = "spell_fire_fireball", ranks = {11078, 11080} },
                ["d"] = { name = "Ignite", icon = "spell_fire_incinerate", ranks = {11119, 11120, 12846} },
                ["e"] = { name = "Fire Power", icon = "spell_fire_immolation", ranks = {18459, 18460, 54734} },
                ["f"] = { name = "Blazing Speed", icon = "spell_fire_burningspeed", ranks = {31641, 31642} },
                ["g"] = { name = "Impact", icon = "spell_fire_meteorstorm", ranks = {11103, 12357} },
                ["h"] = { name = "Cauterize", icon = "spell_fire_rune", ranks = {86948, 86949} },
                ["j"] = { name = "Blast Wave", icon = "spell_holy_excorcism_02", ranks = {11113} },
                ["k"] = { name = "Hot Streak", icon = "ability_mage_hotstreak", ranks = {44445} },
                ["m"] = { name = "Improved Scorch", icon = "spell_fire_soulburn", ranks = {11115, 11367} },
                ["n"] = { name = "Molten Shields", icon = "spell_fire_firearmor", ranks = {11094} },
                ["p"] = { name = "Combustion", icon = "spell_fire_sealoffire", ranks = {11129} },
                ["q"] = { name = "Improved Hot Streak", icon = "ability_mage_hotstreak", ranks = {44446, 44448} },
                ["r"] = { name = "Firestarter", icon = "ability_mage_firestarter", ranks = {86914} },
                ["s"] = { name = "Improved Flamestrike", icon = "spell_fire_selfdestruct", ranks = {84673, 84674} },
                ["t"] = { name = "Dragon's Breath", icon = "inv_misc_head_dragon_01", ranks = {31661} },
                ["v"] = { name = "Molten Fury", icon = "spell_fire_moltenblood", ranks = {31679, 31680, 86880} },
                ["w"] = { name = "Pyromaniac", icon = "spell_fire_burnout", ranks = {34293, 34295} },
                ["z"] = { name = "Critical Mass", icon = "spell_nature_wispheal", ranks = {11095, 12872, 12873} },
                ["x"] = { name = "Living Bomb", icon = "ability_mage_livingbomb", ranks = {44457} },
            },
            [2] = { -- Freezes enemies in their tracks and shatters them with Frost magic.
                ["a"] = { name = "Early Frost", icon = "spell_frost_chillingbolt", ranks = {83049, 83050} },
                ["b"] = { name = "Piercing Ice", icon = "spell_frost_frostbolt", ranks = {11151, 12952, 12953} },
                ["c"] = { name = "Shatter", icon = "spell_frost_frostshock", ranks = {11170, 12982} },
                ["d"] = { name = "Ice Floes", icon = "spell_frost_icefloes", ranks = {31670, 31672, 55094} },
                ["e"] = { name = "Improved Cone of Cold", icon = "spell_frost_glacier", ranks = {11190, 12489} },
                ["f"] = { name = "Piercing Chill", icon = "spell_frost_piercing-chill", ranks = {83156, 83157} },
                ["g"] = { name = "Permafrost", icon = "spell_frost_wisp", ranks = {11175, 12569, 12571} },
                ["h"] = { name = "Ice Shards", icon = "spell_frost_ice-shards", ranks = {11185, 12487} },
                ["j"] = { name = "Icy Veins", icon = "spell_frost_coldhearted", ranks = {12472} },
                ["k"] = { name = "Fingers of Frost", icon = "ability_mage_wintersgrasp", ranks = {44543, 44545, 83074} },
                ["m"] = { name = "Improved Freeze", icon = "spell_frost_summonwaterelemental", ranks = {86259, 86260, 86314} },
                ["n"] = { name = "Enduring Winter", icon = "spell_frost_arcticwinds", ranks = {44561, 86500, 86508} },
                ["p"] = { name = "Cold Snap", icon = "spell_frost_wizardmark", ranks = {11958} },
                ["q"] = { name = "Brain Freeze", icon = "ability_mage_brainfreeze", ranks = {44546, 44548, 44549} },
                ["r"] = { name = "Shattered Barrier", icon = "ability_mage_coldasice", ranks = {44745, 54787} },
                ["s"] = { name = "Ice Barrier", icon = "spell_ice_lament", ranks = {11426} },
                ["t"] = { name = "Reactive Barrier", icon = "spell_frost_manarecharge", ranks = {86303, 86304} },
                ["v"] = { name = "Frostfire Orb", icon = "spell_firefrost-orb", ranks = {84726, 84727} },
                ["w"] = { name = "Deep Freeze", icon = "ability_mage_deepfreeze", ranks = {44572} },
            },
        },
        PALADIN = {
            [0] = { -- Invokes the power of the Light to protect and to heal.
                ["a"] = { name = "Arbiter of the Light", icon = "spell_holy_healingaura", ranks = {20359, 20360} },
                ["b"] = { name = "Protector of the Innocent", icon = "ability_paladin_protectoroftheinnocent", ranks = {20138, 20139, 20140} },
                ["c"] = { name = "Judgements of the Pure", icon = "ability_paladin_judgementofthepure", ranks = {53671, 53673, 54151} },
                ["d"] = { name = "Clarity of Purpose", icon = "spell_paladin_clarityofpurpose", ranks = {85462, 85463, 85464} },
                ["e"] = { name = "Last Word", icon = "spell_holy_holyguidance", ranks = {20234, 20235} },
                ["f"] = { name = "Blazing Light", icon = "spell_holy_holybolt", ranks = {20237, 20238} },
                ["g"] = { name = "Denounce", icon = "spell_holy_excorcism_02", ranks = {31825, 85510} },
                ["h"] = { name = "Divine Favor", icon = "spell_holy_divineillumination", ranks = {31842} },
                ["j"] = { name = "Infusion of Light", icon = "ability_paladin_infusionoflight", ranks = {53569, 53576} },
                ["k"] = { name = "Daybreak", icon = "inv_qirajidol_sun", ranks = {88820, 88821} },
                ["m"] = { name = "Enlightened Judgements", icon = "ability_paladin_enlightenedjudgements", ranks = {53556, 53557} },
                ["n"] = { name = "Beacon of Light", icon = "ability_paladin_beaconoflight", ranks = {53563} },
                ["p"] = { name = "Speed of Light", icon = "paladin_icon_speedoflight", ranks = {85495, 85498, 85499} },
                ["q"] = { name = "Sacred Cleansing", icon = "ability_paladin_sacredcleansing", ranks = {53551} },
                ["r"] = { name = "Conviction", icon = "ability_paladin_conviction", ranks = {20049, 20056, 20057} },
                ["s"] = { name = "Aura Mastery", icon = "spell_holy_auramastery", ranks = {31821} },
                ["t"] = { name = "Paragon of Virtue", icon = "spell_holy_avenginewrath", ranks = {93418, 93417} },
                ["v"] = { name = "Tower of Radiance", icon = "achievement_bg_winsoa", ranks = {84800, 85511, 85512} },
                ["w"] = { name = "Blessed Life", icon = "spell_holy_blessedlife", ranks = {31828, 31829} },
                ["z"] = { name = "Light of Dawn", icon = "spell_paladin_lightofdawn", ranks = {85222} },
            },
            [1] = { -- Uses Holy magic to shield <himself/herself> and defend allies from attackers.
                ["a"] = { name = "Divinity", icon = "spell_holy_blindingheal", ranks = {63646, 63647, 63648} },
                ["b"] = { name = "Seals of the Pure", icon = "inv_mace_46", ranks = {20224, 20225} },
                ["c"] = { name = "Eternal Glory", icon = "inv_torch_thrown", ranks = {87163, 87164} },
                ["d"] = { name = "Judgements of the Just", icon = "ability_paladin_judgementsofthejust", ranks = {53695, 53696} },
                ["e"] = { name = "Toughness", icon = "spell_holy_devotion", ranks = {20143, 20144, 20145} },
                ["f"] = { name = "Improved Hammer of Justice", icon = "spell_holy_sealofmight", ranks = {20487, 20488} },
                ["g"] = { name = "Hallowed Ground", icon = "spell_holy_innerfire", ranks = {84631, 84633} },
                ["h"] = { name = "Sanctuary", icon = "spell_nature_lightningshield", ranks = {20911, 84628, 84629} },
                ["j"] = { name = "Hammer of the Righteous", icon = "ability_paladin_hammeroftherighteous", ranks = {53595} },
                ["k"] = { name = "Wrath of the Lightbringer", icon = "inv_mace_82", ranks = {84635, 84636} },
                ["m"] = { name = "Reckoning", icon = "spell_holy_blessingofstrength", ranks = {20177, 20179} },
                ["n"] = { name = "Shield of the Righteous", icon = "ability_paladin_shieldofvengeance", ranks = {53600} },
                ["p"] = { name = "Grand Crusader", icon = "inv_helmet_74", ranks = {75806, 85043} },
                ["q"] = { name = "Vindication", icon = "spell_holy_vindication", ranks = {26016} },
                ["r"] = { name = "Holy Shield", icon = "classic_spell_holy_blessingofprotection", ranks = {20925} },
                ["s"] = { name = "Guarded by the Light", icon = "ability_paladin_gaurdedbythelight", ranks = {85639, 85646} },
                ["t"] = { name = "Divine Guardian", icon = "spell_holy_powerwordbarrier", ranks = {70940} },
                ["v"] = { name = "Sacred Duty", icon = "spell_holy_divineintervention", ranks = {53709, 53710} },
                ["w"] = { name = "Shield of the Templar", icon = "ability_paladin_shieldofthetemplar", ranks = {31848, 31849, 84854} },
                ["z"] = { name = "Ardent Defender", icon = "spell_holy_ardentdefender", ranks = {31850} },
            },
            [2] = { -- A righteous crusader who judges and punishes opponents with weapons and Holy magic.
                ["a"] = { name = "Eye for an Eye", icon = "spell_holy_eyeforaneye", ranks = {9799, 25988} },
                ["b"] = { name = "Crusade", icon = "spell_holy_crusade", ranks = {31866, 31867, 31868} },
                ["c"] = { name = "Improved Judgement", icon = "ability_paladin_judgementblue", ranks = {87174, 87175} },
                ["d"] = { name = "Guardian's Favor", icon = "spell_holy_sealofprotection", ranks = {20174, 20175} },
                ["e"] = { name = "Rule of Law", icon = "inv_relics_libramofhope", ranks = {85457, 85458, 87461} },
                ["f"] = { name = "Pursuit of Justice", icon = "spell_holy_persuitofjustice", ranks = {26022, 26023} },
                ["g"] = { name = "Communion", icon = "ability_paladin_judgementofthewise", ranks = {31876} },
                ["h"] = { name = "The Art of War", icon = "ability_paladin_artofwar", ranks = {53486, 53488, 87138} },
                ["j"] = { name = "Long Arm of the Law", icon = "ability_paladin_judgementred", ranks = {87168, 87172} },
                ["k"] = { name = "Divine Storm", icon = "ability_paladin_divinestorm", ranks = {53385} },
                ["m"] = { name = "Sacred Shield", icon = "ability_paladin_blessedmending", ranks = {85285} },
                ["n"] = { name = "Sanctity of Battle", icon = "inv_sword_136", ranks = {25956} },
                ["p"] = { name = "Seals of Command", icon = "ability_warrior_innerrage", ranks = {85126} },
                ["q"] = { name = "Sanctified Wrath", icon = "ability_paladin_sanctifiedwrath", ranks = {53375, 90286, 53376} },
                ["r"] = { name = "Selfless Healer", icon = "spell_holy_rune", ranks = {85803, 85804} },
                ["s"] = { name = "Repentance", icon = "spell_holy_prayerofhealing", ranks = {20066} },
                ["t"] = { name = "Divine Purpose", icon = "spell_holy_divinepurpose", ranks = {85117, 86172} },
                ["v"] = { name = "Inquiry of Faith", icon = "ability_paladin_righteousvengeance", ranks = {53380, 53381, 53382} },
                ["w"] = { name = "Acts of Sacrifice", icon = "ability_paladin_blessedhands", ranks = {85446, 85795} },
                ["z"] = { name = "Zealotry", icon = "spell_holy_proclaimchampion_02", ranks = {85696} },
            },
        },
        PRIEST = {
            [0] = { -- Uses magic to shield allies from taking damage as well as heal their wounds.
                ["a"] = { name = "Improved Power Word: Shield", icon = "spell_holy_powerwordshield", ranks = {14748, 14768} },
                ["b"] = { name = "Twin Disciplines", icon = "spell_holy_sealofvengeance", ranks = {47586, 47587, 47588} },
                ["c"] = { name = "Mental Agility", icon = "ability_hibernation", ranks = {14520, 14780, 14781} },
                ["d"] = { name = "Evangelism", icon = "spell_holy_divineillumination", ranks = {81659, 81662} },
                ["e"] = { name = "Archangel", icon = "ability_priest_archangel", ranks = {87151} },
                ["f"] = { name = "Inner Sanctum", icon = "spell_holy_innerfire", ranks = {14747, 14770, 14771} },
                ["g"] = { name = "Soul Warding", icon = "ability_priest_soulwarding", ranks = {63574, 78500} },
                ["h"] = { name = "Renewed Hope", icon = "spell_holy_holyprotection", ranks = {57470, 57472} },
                ["j"] = { name = "Power Infusion", icon = "spell_holy_powerinfusion", ranks = {10060} },
                ["k"] = { name = "Atonement", icon = "ability_priest_atonement", ranks = {14523, 81749} },
                ["m"] = { name = "Inner Focus", icon = "spell_frost_windwalkon", ranks = {89485} },
                ["n"] = { name = "Rapture", icon = "spell_holy_rapture", ranks = {47535, 47536, 47537} },
                ["p"] = { name = "Borrowed Time", icon = "spell_holy_borrowedtime", ranks = {52795, 52797} },
                ["q"] = { name = "Reflective Shield", icon = "ability_priest_reflectiveshield", ranks = {33201, 33202} },
                ["r"] = { name = "Strength of Soul", icon = "spell_holy_ashestoashes", ranks = {89488, 89489} },
                ["s"] = { name = "Divine Aegis", icon = "spell_holy_devineaegis", ranks = {47509, 47511, 47515} },
                ["t"] = { name = "Pain Suppression", icon = "spell_holy_painsupression", ranks = {33206} },
                ["v"] = { name = "Train of Thought", icon = "ability_mage_studentofthemind", ranks = {92295, 92297} },
                ["w"] = { name = "Focused Will", icon = "ability_priest_focusedwill", ranks = {45234, 45243} },
                ["z"] = { name = "Grace", icon = "spell_holy_hopeandgrace", ranks = {47516, 47517} },
                ["x"] = { name = "Power Word: Barrier", icon = "spell_holy_powerwordbarrier", ranks = {62618} },
            },
            [1] = { -- A versatile healer who can reverse damage on individuals or groups and even heal from beyond the grave.
                ["a"] = { name = "Improved Renew", icon = "spell_holy_renew", ranks = {14908, 15020} },
                ["b"] = { name = "Empowered Healing", icon = "spell_holy_greaterheal", ranks = {33158, 33159, 33160} },
                ["c"] = { name = "Divine Fury", icon = "spell_holy_sealofwrath", ranks = {18530, 18531, 18533} },
                ["d"] = { name = "Desperate Prayer", icon = "spell_holy_restoration", ranks = {19236} },
                ["e"] = { name = "Surge of Light", icon = "spell_holy_surgeoflight", ranks = {88687, 88690} },
                ["f"] = { name = "Inspiration", icon = "spell_holy_layonhands", ranks = {14892, 15362} },
                ["g"] = { name = "Divine Touch", icon = "ability_paladin_infusionoflight", ranks = {63534, 63542} },
                ["h"] = { name = "Holy Concentration", icon = "spell_holy_fanaticism", ranks = {34753, 34859} },
                ["j"] = { name = "Lightwell", icon = "spell_holy_summonlightwell", ranks = {724} },
                ["k"] = { name = "Tome of Light", icon = "inv_misc_book_07", ranks = {14898, 81625} },
                ["m"] = { name = "Rapid Renewal", icon = "ability_paladin_blessedmending", ranks = {95649} },
                ["n"] = { name = "Spirit of Redemption", icon = "inv_enchant_essenceeternallarge", ranks = {20711} },
                ["p"] = { name = "Serendipity", icon = "spell_holy_serendipity", ranks = {63730, 63733} },
                ["q"] = { name = "Body and Soul", icon = "spell_holy_symbolofhope", ranks = {64127, 64129} },
                ["r"] = { name = "Chakra", icon = "spell_priest_chakra", ranks = {14751} },
                ["s"] = { name = "Revelations", icon = "ability_priest_bindingprayers", ranks = {88627} },
                ["t"] = { name = "Blessed Resilience", icon = "spell_holy_blessedresillience", ranks = {33142, 33145} },
                ["v"] = { name = "Test of Faith", icon = "spell_holy_testoffaith", ranks = {47558, 47559, 47560} },
                ["w"] = { name = "Heavenly Voice", icon = "ability_priest_heavanlyvoice", ranks = {87430, 87431} },
                ["z"] = { name = "Circle of Healing", icon = "spell_holy_circleofrenewal", ranks = {34861} },
                ["x"] = { name = "Guardian Spirit", icon = "spell_holy_guardianspirit", ranks = {47788} },
            },
            [2] = { -- Uses sinister Shadow magic, especially damage-over-time spells, to eradicate enemies.
                ["a"] = { name = "Darkness", icon = "ability_priest_darkness", ranks = {15259, 15307, 15308} },
                ["b"] = { name = "Improved Shadow Word: Pain", icon = "spell_shadow_shadowwordpain", ranks = {15275, 15317} },
                ["c"] = { name = "Veiled Shadows", icon = "spell_magic_lesserinvisibilty", ranks = {15274, 15311} },
                ["d"] = { name = "Improved Psychic Scream", icon = "spell_shadow_psychicscream", ranks = {15392, 15448} },
                ["e"] = { name = "Improved Mind Blast", icon = "spell_shadow_unholyfrenzy", ranks = {15273, 15312, 15313} },
                ["f"] = { name = "Improved Devouring Plague", icon = "spell_shadow_devouringplague", ranks = {63625, 63626} },
                ["g"] = { name = "Twisted Faith", icon = "spell_shadow_mindtwisting", ranks = {47573, 47577} },
                ["h"] = { name = "Shadowform", icon = "spell_shadow_shadowform", ranks = {15473} },
                ["j"] = { name = "Phantasm", icon = "spell_shadow_twistedfaith", ranks = {47569, 47570} },
                ["k"] = { name = "Harnessed Shadows", icon = "inv_misc_orb_04", ranks = {33191, 78228} },
                ["m"] = { name = "Silence", icon = "ability_priest_silence", ranks = {15487} },
                ["n"] = { name = "Vampiric Embrace", icon = "spell_shadow_unsummonbuilding", ranks = {15286} },
                ["p"] = { name = "Masochism", icon = "spell_shadow_misery", ranks = {88994, 88995} },
                ["q"] = { name = "Mind Melt", icon = "spell_shadow_skull", ranks = {14910, 33371} },
                ["r"] = { name = "Pain and Suffering", icon = "spell_shadow_painandsuffering", ranks = {47580, 47581} },
                ["s"] = { name = "Vampiric Touch", icon = "spell_holy_stoicism", ranks = {34914} },
                ["t"] = { name = "Paralysis", icon = "ability_rogue_masterofsubtlety", ranks = {87192, 87195} },
                ["v"] = { name = "Psychic Horror", icon = "spell_shadow_psychichorrors", ranks = {64044} },
                ["w"] = { name = "Sin and Punishment", icon = "spell_holy_prayerofshadowprotection", ranks = {87099, 87100} },
                ["z"] = { name = "Shadowy Apparition", icon = "ability_priest_shadowyapparition", ranks = {78202, 78203, 78204} },
                ["x"] = { name = "Dispersion", icon = "spell_shadow_dispersion", ranks = {47585} },
            },
        },
        ROGUE = {
            [0] = { -- A deadly master of poisons who dispatches victims with vicious dagger strikes.
                ["a"] = { name = "Deadly Momentum", icon = "ability_rogue_deadlymomentum", ranks = {79121, 79122} },
                ["b"] = { name = "Coup de Grace", icon = "ability_rogue_eviscerate", ranks = {14162, 14163, 14164} },
                ["c"] = { name = "Lethality", icon = "ability_criticalstrike", ranks = {14128, 14132, 14135} },
                ["d"] = { name = "Ruthlessness", icon = "ability_druid_disembowel", ranks = {14156, 14160, 14161} },
                ["e"] = { name = "Quickening", icon = "ability_rogue_quickrecovery", ranks = {31208, 31209} },
                ["f"] = { name = "Puncturing Wounds", icon = "ability_backstab", ranks = {13733, 13865, 13866} },
                ["g"] = { name = "Blackjack", icon = "ability_rogue_blackjack", ranks = {79123, 79125} },
                ["h"] = { name = "Deadly Brew", icon = "ability_rogue_deadlybrew", ranks = {51625, 51626} },
                ["j"] = { name = "Cold Blood", icon = "spell_ice_lament", ranks = {14177} },
                ["k"] = { name = "Vile Poisons", icon = "ability_rogue_feigndeath", ranks = {16513, 16514, 16515} },
                ["m"] = { name = "Deadened Nerves", icon = "ability_rogue_deadenednerves", ranks = {31380, 31382, 31383} },
                ["n"] = { name = "Seal Fate", icon = "ability_rogue_stayofexecution", ranks = {14186, 14190} },
                ["p"] = { name = "Murderous Intent", icon = "spell_shadow_deathscream", ranks = {14158, 14159} },
                ["q"] = { name = "Overkill", icon = "ability_hunter_rapidkilling", ranks = {58426} },
                ["r"] = { name = "Master Poisoner", icon = "ability_creature_poison_06", ranks = {58410} },
                ["s"] = { name = "Improved Expose Armor", icon = "ability_warrior_riposte", ranks = {14168, 14169} },
                ["t"] = { name = "Cut to the Chase", icon = "ability_rogue_cuttothechase", ranks = {51664, 51665, 51667} },
                ["v"] = { name = "Venomous Wounds", icon = "ability_rogue_venomouswounds", ranks = {79133, 79134} },
                ["w"] = { name = "Vendetta", icon = "ability_rogue_deadliness", ranks = {79140} },
            },
            [1] = { -- A swashbuckler who uses agility and guile to stand toe-to-toe with enemies.
                ["a"] = { name = "Improved Recuperate", icon = "ability_rogue_improvedrecuperate", ranks = {79007, 79008} },
                ["b"] = { name = "Improved Sinister Strike", icon = "spell_shadow_ritualofsacrifice", ranks = {13732, 13863, 79004} },
                ["c"] = { name = "Precision", icon = "ability_marksmanship", ranks = {13705, 13832, 13843} },
                ["d"] = { name = "Improved Slice and Dice", icon = "ability_rogue_slicedice", ranks = {14165, 14166} },
                ["e"] = { name = "Improved Sprint", icon = "ability_rogue_sprint", ranks = {13743, 13875} },
                ["f"] = { name = "Aggression", icon = "ability_racial_avatar", ranks = {18427, 18428, 18429} },
                ["g"] = { name = "Improved Kick", icon = "ability_kick", ranks = {13754, 13867} },
                ["h"] = { name = "Lightning Reflexes", icon = "spell_nature_invisibilty", ranks = {13712, 13788, 13789} },
                ["j"] = { name = "Revealing Strike", icon = "inv_sword_97", ranks = {84617} },
                ["k"] = { name = "Reinforced Leather", icon = "ability_rogue_reinforcedleather", ranks = {79077, 79079} },
                ["m"] = { name = "Improved Gouge", icon = "ability_gouge", ranks = {13741, 13793} },
                ["n"] = { name = "Combat Potency", icon = "inv_weapon_shortblade_38", ranks = {35541, 35550, 35551} },
                ["p"] = { name = "Blade Twisting", icon = "ability_rogue_bladetwisting", ranks = {31124, 31126} },
                ["q"] = { name = "Throwing Specialization", icon = "ability_rogue_throwingspecialization", ranks = {5952, 51679} },
                ["r"] = { name = "Adrenaline Rush", icon = "spell_shadow_shadowworddominate", ranks = {13750} },
                ["s"] = { name = "Savage Combat", icon = "ability_creature_disease_03", ranks = {51682, 58413} },
                ["t"] = { name = "Bandit's Guile", icon = "ability_rogue_preyontheweak", ranks = {84652, 84653, 84654} },
                ["v"] = { name = "Restless Blades", icon = "ability_rogue_restlessblades", ranks = {79095, 79096} },
                ["w"] = { name = "Killing Spree", icon = "ability_rogue_murderspree", ranks = {51690} },
            },
            [2] = { -- A dark stalker who leaps from the shadows to ambush <his/her> unsuspecting prey.
                ["a"] = { name = "Nightstalker", icon = "ability_stealth", ranks = {13975, 14062} },
                ["b"] = { name = "Improved Ambush", icon = "ability_rogue_ambush", ranks = {14079, 14080, 84661} },
                ["c"] = { name = "Relentless Strikes", icon = "ability_warrior_decisivestrike", ranks = {14179, 58422, 58423} },
                ["d"] = { name = "Elusiveness", icon = "spell_magic_lesserinvisibilty", ranks = {13981, 14066} },
                ["e"] = { name = "Waylay", icon = "ability_rogue_waylay", ranks = {51692, 51696} },
                ["f"] = { name = "Opportunity", icon = "ability_rogue_bloodsplatter", ranks = {14057, 14072, 79141} },
                ["g"] = { name = "Initiative", icon = "spell_shadow_fumble", ranks = {13976, 13979} },
                ["h"] = { name = "Energetic Recovery", icon = "ability_rogue_sturdyrecuperate", ranks = {79150, 79151, 79152} },
                ["j"] = { name = "Find Weakness", icon = "ability_rogue_findweakness", ranks = {51632, 91023} },
                ["k"] = { name = "Hemorrhage", icon = "spell_shadow_lifedrain", ranks = {16511} },
                ["m"] = { name = "Honor Among Thieves", icon = "ability_rogue_honoramongstthieves", ranks = {51698, 51700, 51701} },
                ["n"] = { name = "Premeditation", icon = "spell_shadow_possession", ranks = {14183} },
                ["p"] = { name = "Enveloping Shadows", icon = "ability_rogue_envelopingshadows", ranks = {31211, 31212, 31213} },
                ["q"] = { name = "Cheat Death", icon = "ability_rogue_cheatdeath", ranks = {31228, 31229, 31230} },
                ["r"] = { name = "Preparation", icon = "ability_rogue_preparation", ranks = {14185} },
                ["s"] = { name = "Sanguinary Vein", icon = "ability_rogue_sanguinaryvein", ranks = {79146, 79147} },
                ["t"] = { name = "Slaughter from the Shadows", icon = "ability_rogue_slaughterfromtheshadows", ranks = {51708, 51709, 51710} },
                ["v"] = { name = "Serrated Blades", icon = "inv_sword_17", ranks = {14171, 14172} },
                ["w"] = { name = "Shadow Dance", icon = "ability_rogue_shadowdance", ranks = {51713} },
            },
        },
        SHAMAN = {
            [0] = { -- A spellcaster who harnesses the destructive forces of nature and the elements.
                ["a"] = { name = "Acuity", icon = "spell_nature_astralrecalgroup", ranks = {17485, 17486, 17487} },
                ["b"] = { name = "Convection", icon = "spell_shaman_convection", ranks = {16039, 16109} },
                ["c"] = { name = "Concussion", icon = "spell_fire_fireball", ranks = {16035, 16105, 16106} },
                ["d"] = { name = "Call of Flame", icon = "spell_fire_immolation", ranks = {16038, 16160} },
                ["e"] = { name = "Elemental Warding", icon = "spell_nature_spiritarmor", ranks = {28996, 28997, 28998} },
                ["f"] = { name = "Reverberation", icon = "spell_frost_frostward", ranks = {16040, 16113} },
                ["g"] = { name = "Elemental Precision", icon = "spell_nature_elementalprecision_1", ranks = {30672, 30673, 30674} },
                ["h"] = { name = "Rolling Thunder", icon = "spell_nature_callstorm", ranks = {88756, 88764} },
                ["j"] = { name = "Elemental Focus", icon = "spell_shadow_manaburn", ranks = {16164} },
                ["k"] = { name = "Elemental Reach", icon = "spell_nature_stormreach", ranks = {28999, 29000} },
                ["m"] = { name = "Elemental Oath", icon = "spell_shaman_elementaloath", ranks = {51466, 51470} },
                ["n"] = { name = "Lava Flows", icon = "spell_shaman_lavaflow", ranks = {51480, 51481, 51482} },
                ["p"] = { name = "Fulmination", icon = "spell_nature_unrelentingstorm", ranks = {88766} },
                ["q"] = { name = "Elemental Mastery", icon = "spell_nature_wispheal", ranks = {16166} },
                ["r"] = { name = "Earth's Grasp", icon = "spell_nature_stranglevines", ranks = {51483, 51485} },
                ["s"] = { name = "Totemic Wrath", icon = "spell_fire_totemofwrath", ranks = {77746} },
                ["t"] = { name = "Feedback", icon = "ability_vehicle_electrocharge", ranks = {86183, 86184, 86185} },
                ["v"] = { name = "Lava Surge", icon = "spell_shaman_lavasurge", ranks = {77755, 77756} },
                ["w"] = { name = "Earthquake", icon = "spell_shaman_earthquake", ranks = {61882} },
            },
            [1] = { -- A totemic warrior who strikes foes with weapons imbued with elemental power.
                ["a"] = { name = "Elemental Weapons", icon = "spell_fire_flametounge", ranks = {16266, 29079} },
                ["b"] = { name = "Focused Strikes", icon = "spell_shaman_focusedstrikes", ranks = {77536, 77537, 77538} },
                ["c"] = { name = "Improved Shields", icon = "spell_nature_lightningshield", ranks = {16261, 16290, 51881} },
                ["d"] = { name = "Elemental Devastation", icon = "classic_spell_fire_elementaldevastation", ranks = {30160, 29179, 29180} },
                ["e"] = { name = "Flurry", icon = "ability_ghoulfrenzy", ranks = {16256, 16281, 16282} },
                ["f"] = { name = "Ancestral Swiftness", icon = "spell_lifegivingspeed", ranks = {16262, 16287} },
                ["g"] = { name = "Totemic Reach", icon = "spell_nature_agitatingtotem", ranks = {86935, 86936} },
                ["h"] = { name = "Toughness", icon = "spell_holy_devotion", ranks = {16252, 16306, 16307} },
                ["j"] = { name = "Stormstrike", icon = "ability_shaman_stormstrike", ranks = {17364} },
                ["k"] = { name = "Static Shock", icon = "spell_shaman_staticshock", ranks = {51525, 51526, 51527} },
                ["m"] = { name = "Frozen Power", icon = "spell_fire_bluecano", ranks = {63373, 63374} },
                ["n"] = { name = "Seasoned Winds", icon = "spell_nature_elementalabsorption", ranks = {16086, 16544} },
                ["p"] = { name = "Searing Flames", icon = "spell_fire_searingtotem", ranks = {77655, 77656, 77657} },
                ["q"] = { name = "Earthen Power", icon = "spell_nature_earthelemental_totem", ranks = {51523, 51524} },
                ["r"] = { name = "Shamanistic Rage", icon = "spell_nature_shamanrage", ranks = {30823} },
                ["s"] = { name = "Unleashed Rage", icon = "spell_nature_unleashedrage", ranks = {30802, 30808} },
                ["t"] = { name = "Maelstrom Weapon", icon = "spell_shaman_maelstromweapon", ranks = {51528, 51529, 51530} },
                ["v"] = { name = "Improved Lava Lash", icon = "spell_shaman_improvelavalash", ranks = {77700, 77701} },
                ["w"] = { name = "Feral Spirit", icon = "spell_shaman_feralspirit", ranks = {51533} },
            },
            [2] = { -- A healer who calls upon ancestral spirits and the cleansing power of water to mend allies' wounds.
                ["a"] = { name = "Ancestral Resolve", icon = "spell_nature_rune", ranks = {77829, 77830} },
                ["b"] = { name = "Tidal Focus", icon = "spell_frost_manarecharge", ranks = {16179, 16214, 16215} },
                ["c"] = { name = "Spark of Life", icon = "spell_nature_wispsplodegreen", ranks = {84846, 84847, 84848} },
                ["d"] = { name = "Resurgence", icon = "ability_shaman_watershield", ranks = {16180, 16196} },
                ["e"] = { name = "Totemic Focus", icon = "spell_nature_moonglow", ranks = {16173, 16222} },
                ["f"] = { name = "Focused Insight", icon = "spell_shaman_measuredinsight", ranks = {77794, 77795, 77796} },
                ["g"] = { name = "Nature's Guardian", icon = "spell_nature_natureguardian", ranks = {30881, 30883, 30884} },
                ["h"] = { name = "Ancestral Healing", icon = "spell_nature_undyingstrength", ranks = {16176, 16235} },
                ["j"] = { name = "Nature's Swiftness", icon = "spell_nature_ravenform", ranks = {16188} },
                ["k"] = { name = "Nature's Blessing", icon = "spell_nature_natureblessing", ranks = {30867, 30868, 30869} },
                ["m"] = { name = "Soothing Rains", icon = "spell_nature_giftofthewaterspirit", ranks = {16187, 16205} },
                ["n"] = { name = "Improved Cleanse Spirit", icon = "ability_shaman_cleansespirit", ranks = {77130} },
                ["p"] = { name = "Cleansing Waters", icon = "spell_nature_regeneration_02", ranks = {86959, 86962} },
                ["q"] = { name = "Ancestral Awakening", icon = "spell_shaman_ancestralawakening", ranks = {51556, 51557, 51558} },
                ["r"] = { name = "Mana Tide Totem", icon = "spell_frost_summonwaterelemental", ranks = {16190} },
                ["s"] = { name = "Telluric Currents", icon = "spell_lightning_lightningbolt01", ranks = {82984, 82988} },
                ["t"] = { name = "Spirit Link Totem", icon = "spell_shaman_spiritlink", ranks = {98008} },
                ["v"] = { name = "Tidal Waves", icon = "spell_shaman_tidalwaves", ranks = {51562, 51563, 51564} },
                ["w"] = { name = "Blessing of the Eternals", icon = "spell_shaman_blessingofeternals", ranks = {51554, 51555} },
                ["z"] = { name = "Riptide", icon = "spell_nature_riptide", ranks = {61295} },
            },
        },
        WARLOCK = {
            [0] = { -- A master of Shadow magic who specializes in fear, drains and damage-over-time spells.
                ["a"] = { name = "Doom and Gloom", icon = "spell_shadow_curseofsargeras", ranks = {18827, 18829} },
                ["b"] = { name = "Improved Life Tap", icon = "spell_shadow_burningspirit", ranks = {18182, 18183} },
                ["c"] = { name = "Improved Corruption", icon = "spell_shadow_abominationexplosion", ranks = {17810, 17811, 17812} },
                ["d"] = { name = "Jinx", icon = "ability_warlock_jinx", ranks = {18179, 85479} },
                ["e"] = { name = "Soul Siphon", icon = "ability_warlock_soulsiphon", ranks = {17804, 17805} },
                ["f"] = { name = "Siphon Life", icon = "spell_shadow_requiem", ranks = {63108, 86667} },
                ["g"] = { name = "Curse of Exhaustion", icon = "spell_shadow_grimward", ranks = {18223} },
                ["h"] = { name = "Improved Fear", icon = "spell_shadow_possession", ranks = {53754, 53759} },
                ["j"] = { name = "Eradication", icon = "ability_warlock_eradication", ranks = {47195, 47196, 47197} },
                ["k"] = { name = "Improved Howl of Terror", icon = "spell_shadow_deathscream", ranks = {30054, 30057} },
                ["m"] = { name = "Soul Swap", icon = "ability_warlock_soulswap", ranks = {86121} },
                ["n"] = { name = "Shadow Embrace", icon = "spell_shadow_shadowembrace", ranks = {32385, 32387, 32392} },
                ["p"] = { name = "Death's Embrace", icon = "spell_shadow_deathsembrace", ranks = {47198, 47199, 47200} },
                ["q"] = { name = "Nightfall", icon = "spell_shadow_twilight", ranks = {18094, 18095} },
                ["r"] = { name = "Soulburn: Seed of Corruption", icon = "spell_shadow_seedofdestruction", ranks = {86664} },
                ["s"] = { name = "Everlasting Affliction", icon = "ability_warlock_everlastingaffliction", ranks = {47201, 47202, 47203} },
                ["t"] = { name = "Pandemic", icon = "spell_shadow_lastingaffliction", ranks = {85099, 85100} },
                ["v"] = { name = "Haunt", icon = "ability_warlock_haunt", ranks = {48181} },
            },
            [1] = { -- A warlock who uses both Fire and Shadow magic along with powerful demons.
                ["a"] = { name = "Demonic Embrace", icon = "spell_shadow_metamorphosis", ranks = {18697, 18698, 18699} },
                ["b"] = { name = "Dark Arts", icon = "ability_warlock_darkarts", ranks = {18694, 85283, 85284} },
                ["c"] = { name = "Fel Synergy", icon = "spell_shadow_felmending", ranks = {47230, 47231} },
                ["d"] = { name = "Demonic Rebirth", icon = "spell_shadow_demonictactics", ranks = {88446, 88447} },
                ["e"] = { name = "Mana Feed", icon = "spell_shadow_manafeed", ranks = {30326, 85175} },
                ["f"] = { name = "Demonic Aegis", icon = "spell_shadow_ragingscream", ranks = {30143, 30144} },
                ["g"] = { name = "Master Summoner", icon = "spell_shadow_impphaseshift", ranks = {18709, 18710} },
                ["h"] = { name = "Impending Doom", icon = "spell_nature_removecurse", ranks = {85106, 85107, 85108} },
                ["j"] = { name = "Demonic Empowerment", icon = "ability_warlock_demonicempowerment", ranks = {47193} },
                ["k"] = { name = "Improved Health Funnel", icon = "spell_shadow_lifedrain", ranks = {18703, 18704} },
                ["m"] = { name = "Molten Core", icon = "ability_warlock_moltencore", ranks = {47245, 47246, 47247} },
                ["n"] = { name = "Hand of Gul'dan", icon = "inv_summerfest_firespirit", ranks = {71521} },
                ["p"] = { name = "Aura of Foreboding", icon = "spell_shadow_sealofkings", ranks = {89604, 89605} },
                ["q"] = { name = "Ancient Grimoire", icon = "ability_warlock_ancientgrimoire", ranks = {85109, 85110} },
                ["r"] = { name = "Inferno", icon = "ability_warlock_inferno", ranks = {85105} },
                ["s"] = { name = "Decimation", icon = "spell_fire_fireball02", ranks = {63156, 63158} },
                ["t"] = { name = "Cremation", icon = "ability_warlock_cremation", ranks = {85103, 85104} },
                ["v"] = { name = "Demonic Pact", icon = "spell_shadow_demonicpact", ranks = {47236} },
                ["w"] = { name = "Metamorphosis", icon = "spell_shadow_demonform", ranks = {59672} },
            },
            [2] = { -- Calls down demonic fire to burn and demolish enemies.
                ["a"] = { name = "Bane", icon = "spell_shadow_deathpact", ranks = {17788, 17789, 17790} },
                ["b"] = { name = "Shadow and Flame", icon = "spell_shadow_shadowandflame", ranks = {17793, 17796, 17801} },
                ["c"] = { name = "Improved Immolate", icon = "spell_fire_immolation", ranks = {17815, 17833} },
                ["d"] = { name = "Aftermath", icon = "spell_fire_fire", ranks = {85113, 85114} },
                ["e"] = { name = "Emberstorm", icon = "spell_fire_selfdestruct", ranks = {17954, 17955} },
                ["f"] = { name = "Improved Searing Pain", icon = "spell_fire_soulburn", ranks = {17927, 17929} },
                ["g"] = { name = "Improved Soul Fire", icon = "spell_fire_fireball02", ranks = {18119, 18120} },
                ["h"] = { name = "Backdraft", icon = "ability_warlock_backdraft", ranks = {47258, 47259, 47260} },
                ["j"] = { name = "Shadowburn", icon = "spell_shadow_scourgebuild", ranks = {17877} },
                ["k"] = { name = "Burning Embers", icon = "ability_warlock_burningembers", ranks = {91986, 85112} },
                ["m"] = { name = "Soul Leech", icon = "spell_shadow_soulleech_3", ranks = {30293, 30295} },
                ["n"] = { name = "Backlash", icon = "spell_fire_playingwithfire", ranks = {34935, 34938, 34939} },
                ["p"] = { name = "Nether Ward", icon = "spell_fire_felfireward", ranks = {91713} },
                ["q"] = { name = "Fire and Brimstone", icon = "ability_warlock_fireandbrimstone", ranks = {47266, 47267, 47268} },
                ["r"] = { name = "Shadowfury", icon = "spell_shadow_shadowfury", ranks = {30283} },
                ["s"] = { name = "Nether Protection", icon = "spell_shadow_netherprotection", ranks = {30299, 30301} },
                ["t"] = { name = "Empowered Imp", icon = "ability_warlock_empoweredimp", ranks = {47220, 47221} },
                ["v"] = { name = "Bane of Havoc", icon = "ability_warlock_baneofhavoc", ranks = {80240} },
                ["w"] = { name = "Chaos Bolt", icon = "ability_warlock_chaosbolt", ranks = {50796} },
            },
        },
        WARRIOR = {
            [0] = { -- A battle-hardened master of two-handed weapons, using mobility and overpowering attacks to strike <his/her> opponents down.
                ["a"] = { name = "War Academy", icon = "ability_warrior_unrelentingassault", ranks = {84570, 84571, 84572} },
                ["b"] = { name = "Field Dressing", icon = "inv_misc_bandage_05", ranks = {84579, 84580} },
                ["c"] = { name = "Blitz", icon = "warrior_talent_icon_blitz", ranks = {80976, 80977} },
                ["d"] = { name = "Tactical Mastery", icon = "spell_nature_enchantarmor", ranks = {12295, 12676} },
                ["e"] = { name = "Second Wind", icon = "ability_hunter_harass", ranks = {29834, 29838} },
                ["f"] = { name = "Deep Wounds", icon = "ability_backstab", ranks = {12834, 12849, 12867} },
                ["g"] = { name = "Drums of War", icon = "achievement_bg_winwsg_3-0", ranks = {12290, 12963} },
                ["h"] = { name = "Taste for Blood", icon = "ability_rogue_hungerforblood", ranks = {56636, 56637, 56638} },
                ["j"] = { name = "Sweeping Strikes", icon = "ability_rogue_slicedice", ranks = {12328} },
                ["k"] = { name = "Impale", icon = "ability_searingarrow", ranks = {16493, 16494} },
                ["m"] = { name = "Improved Hamstring", icon = "ability_shockwave", ranks = {12289, 12668} },
                ["n"] = { name = "Improved Slam", icon = "ability_warrior_decisivestrike", ranks = {86655, 12330} },
                ["p"] = { name = "Deadly Calm", icon = "achievement_boss_kingymiron", ranks = {85730} },
                ["q"] = { name = "Blood Frenzy", icon = "ability_warrior_bloodfrenzy", ranks = {29836, 29859} },
                ["r"] = { name = "Lambs to the Slaughter", icon = "warrior_talent_icon_lambstotheslaughter", ranks = {84583, 84587, 84588} },
                ["s"] = { name = "Juggernaut", icon = "ability_warrior_bullrush", ranks = {64976} },
                ["t"] = { name = "Sudden Death", icon = "ability_warrior_improveddisciplines", ranks = {29723, 29725} },
                ["v"] = { name = "Wrecking Crew", icon = "ability_warrior_trauma", ranks = {46867, 56611} },
                ["w"] = { name = "Throwdown", icon = "inv_mace_62", ranks = {85388} },
                ["z"] = { name = "Bladestorm", icon = "ability_warrior_bladestorm", ranks = {46924} },
            },
            [1] = { -- A furious berserker wielding a weapon in each hand, unleashing a flurry of attacks to carve <his/her> opponents to pieces.
                ["a"] = { name = "Blood Craze", icon = "spell_shadow_summonimp", ranks = {16487, 16489, 16492} },
                ["b"] = { name = "Battle Trance", icon = "inv_helmet_06", ranks = {12322, 85741, 85742} },
                ["c"] = { name = "Cruelty", icon = "ability_rogue_eviscerate", ranks = {12320, 12852} },
                ["d"] = { name = "Executioner", icon = "inv_sword_48", ranks = {20502, 20503} },
                ["e"] = { name = "Booming Voice", icon = "spell_nature_purge", ranks = {12321, 12835} },
                ["f"] = { name = "Rude Interruption", icon = "ability_warrior_commandingshout", ranks = {61216, 61221} },
                ["g"] = { name = "Piercing Howl", icon = "spell_shadow_deathscream", ranks = {12323} },
                ["h"] = { name = "Flurry", icon = "ability_ghoulfrenzy", ranks = {12319, 12971, 12972} },
                ["j"] = { name = "Death Wish", icon = "spell_shadow_deathpact", ranks = {12292} },
                ["k"] = { name = "Enrage", icon = "spell_shadow_unholyfrenzy", ranks = {12317, 13045, 13046} },
                ["m"] = { name = "Die by the Sword", icon = "inv_sword_86", ranks = {81913, 81914} },
                ["n"] = { name = "Raging Blow", icon = "ability_hunter_swiftstrike", ranks = {85288} },
                ["p"] = { name = "Rampage", icon = "ability_warrior_rampage", ranks = {29801} },
                ["q"] = { name = "Heroic Fury", icon = "warrior_talent_icon_deadlycalm", ranks = {60970} },
                ["r"] = { name = "Furious Attacks", icon = "ability_warrior_furiousresolve", ranks = {46910} },
                ["s"] = { name = "Meat Cleaver", icon = "warrior_talent_icon_mastercleaver", ranks = {12329, 12950} },
                ["t"] = { name = "Intensify Rage", icon = "warrior_talent_icon_furyintheblood", ranks = {46908, 46909} },
                ["v"] = { name = "Bloodsurge", icon = "ability_warrior_bloodsurge", ranks = {46913, 46914, 46915} },
                ["w"] = { name = "Skirmisher", icon = "warrior_talent_icon_skirmisher", ranks = {29888, 29889} },
                ["z"] = { name = "Titan's Grip", icon = "ability_warrior_titansgrip", ranks = {46917} },
                ["x"] = { name = "Single-Minded Fury", icon = "warrior_talent_icon_singlemindedfury", ranks = {81099} },
            },
            [2] = { -- A stalwart protector who uses a shield to safeguard <himself/herself> and <his/her> allies.
                ["a"] = { name = "Incite", icon = "ability_warrior_incite", ranks = {50685, 50686, 50687} },
                ["b"] = { name = "Toughness", icon = "spell_holy_devotion", ranks = {12299, 12761, 12762} },
                ["c"] = { name = "Blood and Thunder", icon = "warrior_talent_icon_bloodandthunder", ranks = {84614, 84615} },
                ["d"] = { name = "Shield Specialization", icon = "inv_shield_06", ranks = {12298, 12724, 12725} },
                ["e"] = { name = "Shield Mastery", icon = "ability_warrior_shieldguard", ranks = {29598, 84607, 84608} },
                ["f"] = { name = "Hold the Line", icon = "achievement_bg_defendxtowers_av", ranks = {84604, 84621} },
                ["g"] = { name = "Gag Order", icon = "inv_axe_66", ranks = {12311, 12958} },
                ["h"] = { name = "Last Stand", icon = "spell_holy_ashestoashes", ranks = {12975} },
                ["j"] = { name = "Concussion Blow", icon = "ability_thunderbolt", ranks = {12809} },
                ["k"] = { name = "Bastion of Defense", icon = "ability_defend", ranks = {29593, 29594} },
                ["m"] = { name = "Warbringer", icon = "ability_warrior_warbringer", ranks = {57499} },
                ["n"] = { name = "Improved Revenge", icon = "ability_warrior_revenge", ranks = {12797, 12799} },
                ["p"] = { name = "Devastate", icon = "inv_sword_11", ranks = {20243} },
                ["q"] = { name = "Impending Victory", icon = "ability_warrior_devastate", ranks = {80128, 80129} },
                ["r"] = { name = "Thunderstruck", icon = "warrior_talent_icon_thunderstruck", ranks = {80979, 80980} },
                ["s"] = { name = "Vigilance", icon = "ability_warrior_vigilance", ranks = {50720} },
                ["t"] = { name = "Heavy Repercussions", icon = "inv_shield_01", ranks = {86894, 86896} },
                ["v"] = { name = "Safeguard", icon = "ability_warrior_safeguard", ranks = {46945, 46949} },
                ["w"] = { name = "Sword and Board", icon = "ability_warrior_swordandboard", ranks = {46951, 46952, 46953} },
                ["z"] = { name = "Shockwave", icon = "ability_warrior_shockwave", ranks = {46968} },
            },
        },
    },
}
